import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import SmoothScroll from "@/components/SmoothScroll";
import localFont from "next/font/local";
import Footer from "@/components/layout/Footer";
import CustomCursor from "@/components/CustomCursor";

const pit = localFont({
  src: [
    {
      path: "../assets/fonts/Pit/Pit-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/Pit/Pit-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/Pit/Pit-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-pit",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pit.variable} h-full antialiased`}>
      <SmoothScroll>
        <body className="">
          <CustomCursor />
          <Header />
          <main>{children}</main>
        </body>
      </SmoothScroll>
    </html>
  );
}
